### ISSUE TITLE
Novelty Search improvement

### ISSUE THREAD

**Issue by anguyen8** [jbmouret/sferes2#17]
Hi Mouret,

Thanks a lot for including a Novelty Search version in Sferes. I've found it very close to the description in NS paper.
I find the following issues that you might want to fix:

1. In this file: [sferes/modif/novelty.hpp](https://github.com/jbmouret/sferes2/blob/master/sferes/modif/novelty.hpp), after lowering the `rho_min`, I think we need to reset the `_not_added` to be 0; otherwise every generation after this, the accumulated `_not_added` will always be larger than `Params::novelty::stalled_tresh`, resulting in `_rho_min` keeps getting lowered.

     ```java
     // update rho_min
     if (_not_added > Params::novelty::stalled_tresh)//2500
     {
        _rho_min *= 0.95;
       _not_added = 0; // <--- suggested change
     }
    ```

2. I find that after satisfying this check `(n > _rho_min || misc::rand<float>() < Params::novelty::add_to_archive_prob)` (in the code below), one individual will be added directly to the archive. However, there is a chance that this individual is exactly the same as one already in the archive or very close to one in the archive (distance ~ 0).

```java
if (n > _rho_min
              || misc::rand<float>() < Params::novelty::add_to_archive_prob) {
            _archive.push_back(ea.pop()[i]);
            _not_added = 0;
            ++added;
          }
```

So I'm wondering if adding another check condition would help the search more efficient. 
What do you think?

Best,

Again, I really appreciate such a great framework you created!

**Comment by jbmouret** [comment]
Hi Ahn

Thank you for your feedback.

On Jan 23, 2015, at 17:52, Anh Nguyen <notifications@github.com> wrote:
> 	• In this file: sferes/modif/novelty.hpp, after lowering the rho_min, I think we need to reset the _not_added to be 0; otherwise every generation after this, the accumulated _not_added will always be larger than Params::novelty::stalled_tresh, resulting in _rho_min keeps getting lowered.
> 
>  // update rho_min
> 
>  
> if (_not_added > Params::novelty::stalled_tresh)//2500
> 
>  {
>     _rho_min 
> *= 0.95
> ;
>    _not_added 
> = 0; // <--- suggested change
> 
>  }

Done. Thank you. Note that you may want to have a lower threshold in this case: if you start with rho_min that is too high, you will need a lot of evaluation before reaching the “right value”.

> 	• I find that after satisfying this check (n > _rho_min || misc::rand<float>() < Params::novelty::add_to_archive_prob) (in the code below), one individual will be added directly to the archive. However, there is a chance that this individual is exactly the same as one already in the archive or very close to one in the archive (distance ~ 0).
> 
> if (n >
>  _rho_min
>               
> || misc::rand<float>() < Params::novelty::
> add_to_archive_prob) {
>             _archive
> .push_back(ea.
> pop()[i]);
>             _not_added 
> = 0
> ;
>             
> ++
> added;
>           }
> 
> So I'm wondering if adding another check condition would help the search more efficient. 
> What do you think?

That’s a good point but it would also add a new parameter (the threshold) and I don’t think it is in the original novelty search paper. 

best regards,
— Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by anguyen8** [comment]
>Note that you may want to have a lower threshold in this case: if you start with rho_min that is too high, you will need a lot of evaluation before reaching the “right value”.

This piece of advice is very useful, thank you!
