### ISSUE TITLE
Libboost libraries installed but not detected.

### ISSUE THREAD

**Issue by PabloGN** [jbmouret/sferes2#20]
In ubuntu 14.04 LTS I have installed libboost-all-dev but I get:

$  ./waf configure
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Checking for g++                         : ok  
boost headers                            : Version 1_54 (/usr/include) 
library boost_serialization              : not found 
library boost_filesystem                 : not found 
library boost_system                     : not found 
library boost_unit_test_framework        : not found 
library boost_program_options            : not found 
library boost_graph                      : not found 
library boost_mpi                        : not found 
library boost_python                     : not found 
library boost_thread                     : not found 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header tbb/parallel_for.h   : ok /usr/include 
Checking for library libtbb              : ok /usr/lib 
Checking for header mpi.h                : ok /usr/include/mpi 
Checking for SDL (optional)              : ok 
Checking for header Eigen/Core           : ok /usr/include/eigen3 
Check for program ode-config             : /usr/bin/ode-config 
Checking for ODE (optional)              : ok 
Checking for GSL (optional)              : ok 

--- configuration ---
compiler:
 * CXX: gcc
boost version: 1_54
mpi: False
Compilation flags :
 * default:
   CXXFLAGS : -D_REENTRANT -Wall -fPIC -ftemplate-depth-1024 -Wno-sign-compare -Wno-deprecated  -Wno-unused -DUSE_SDL -DEIGEN3_ENABLED -DSFERES_ROOT="/home/pablo/Dev/sferes2"  -DNDEBUG -O3 -ffast-math 
   LINKFLAGS: 
 * debug:
   CXXFLAGS : -D_REENTRANT -Wall -fPIC -ftemplate-depth-1024 -Wno-sign-compare -Wno-deprecated  -Wno-unused -DUSE_SDL -DEIGEN3_ENABLED -DSFERES_ROOT="/home/pablo/Dev/sferes2" -O1 -ggdb3 -DDBG_ENABLED 
   LINKFLAGS: 
 
--- license ---
Sferes2 is distributed under the CECILL license (GPL-compatible)
Please check the accompagnying COPYING file or http://www.cecill.info/
'configure' finished successfully (0.402s)

Some people say that Boost is broken and it is not possible to check Boost versions. Can we avoid it?
conf.check_boost(lib='serialization filesystem system unit_test_framework program_options graph mpi python thread', min_version='1.35')

**Comment by PabloGN** [comment]
SOLVED (Ubuntu 14.04LTS):
In /usr do:
sudo ln -s lib/x86_64-linux-gnu/ lib64
and then it works:
./waf configure --boost-libs=/usr/lib64

**Comment by jbmouret** [comment]
Thank you. The issue is indeed that the new Ubuntu puts he libs in a lib64 folder that waf does not check. We will work on this issue to avoid the need for the symbolic link.
